server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soap_task
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
